In [1]:
import pandas as pd

### **unit data sheet**

In [2]:
unitdata_df = pd.read_excel('/Users/sophiekim/Desktop/msds/ds 5030/project/emissions_by_unit_and_fuel_type_c_d_aa.xlsb', engine='pyxlsb', skiprows=6, sheet_name='UNIT_DATA')

unitdata_df.head()

,Facility Id,FRS Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,Unit Type,Unit Reporting Method,Unit Maximum Rated Heat Input Capacity (mmBTU/hr),Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
0,1001155,1.100004e+11,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199.0,2023,C,Chemicals,GP-1,NaN,Tier1/2/3,91.8,64740.5,30.50,36.356,0.0
1,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130.0,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30.0,3304.7,1.50,1.788,0.0
2,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130.0,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.01,OCS (Other combustion source),Tier1/2/3,30.0,0.2,0.00,0.000,0.0
3,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130.0,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.02,OCS (Other combustion source),Tier1/2/3,30.0,175.0,0.00,0.000,0.0
4,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130.0,2017,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,OCS (Other combustion source),Tier1/2/3,30.0,9106.1,4.25,5.066,0.0

In [3]:
unitdata_df.columns

Index(['Facility Id', 'FRS Id', 'Facility Name', 'City', 'State',
       'Primary NAICS Code', 'Reporting Year', 'Industry Type (subparts)',
       'Industry Type (sectors)', 'Unit Name', 'Unit Type',
       'Unit Reporting Method',
       'Unit Maximum Rated Heat Input Capacity (mmBTU/hr)',
       'Unit CO2 emissions (non-biogenic) ', 'Unit Methane (CH4) emissions ',
       'Unit Nitrous Oxide (N2O) emissions ',
       'Unit Biogenic CO2 emissions (metric tons)'],
      dtype='object')

In [4]:
unitdata_df['Unit Type'] = unitdata_df['Unit Type'].astype(str).str.strip()

In [5]:
# group by industry type & summing by all the emissions

emissions_cols = ['Unit CO2 emissions (non-biogenic) ', 'Unit Methane (CH4) emissions ',
       'Unit Nitrous Oxide (N2O) emissions ',
       'Unit Biogenic CO2 emissions (metric tons)']


emissions_by_unit = unitdata_df.groupby('Unit Type')[emissions_cols].sum()
emissions_by_unit

,Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
Unit Type,,,,
"BFB (Boiler, bubbling fluidized bed)",7.501641e+06,1.502575e+05,5.714678e+05,4.514767e+07
C (Calciner),2.088842e+07,3.147975e+04,5.901145e+04,1.753900e+03
"CCCT (CC (Turbine, combined cycle))",3.271796e+08,2.248791e+05,3.987286e+05,2.296875e+05
CF (Cyclone Furnace),3.656796e+06,8.525000e+03,1.619988e+04,0.000000e+00
"CFB (Boiler, circulating fluidized bed)",2.288699e+08,6.293340e+05,1.132553e+06,1.051173e+07
CH (Comfort heater),1.373336e+06,1.094024e+03,1.258893e+03,1.588697e+04
COB (By-product recovery coke oven battery combustion stacks (§98.172)),4.658214e+06,1.148500e+03,2.942452e+03,0.000000e+00
"CatH (Heater, catalytic)",1.515756e+05,7.080000e+01,8.344000e+01,0.000000e+00
Chemical Recovery Combustion Unit,9.804860e+05,2.543180e+04,5.375111e+04,0.000000e+00
Chemical Recovery Furnace,2.219857e+07,2.399005e+06,5.050611e+06,0.000000e+00
Electricity Generator,2.278823e+10,3.946432e+07,8.319875e+07,5.305229e+07
F (Furnace),1.900176e+08,2.525857e+05,5.613068e+05,9.440790e+04
FLR (Flare),3.240767e+05,9.837500e+02,2.330658e+03,5.440097e+05
FeFL (Subpart Q - ladle reheater),2.464000e+04,1.150000e+01,1.370800e+01,0.000000e+00
Flare,2.865700e+03,1.000000e+00,1.192000e+00,0.000000e+00
"HMH (Heater, heat medium for heat exchange)",6.844930e+06,6.957098e+03,1.521542e+04,0.000000e+00
HPPU (hydrogen production process units),3.469095e+06,1.792500e+03,2.251688e+03,0.000000e+00
"HWH (Heater, hot water)",7.148703e+05,3.335161e+02,4.521426e+02,3.280000e+01
"ICI (Incinerator, commercial and industrial)",7.168665e+06,1.738200e+04,2.871909e+04,8.069027e+05
IFCE (Direct fired industrial food cooking equipment),5.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00
IGCC (Integrated gasification combined cycle),7.419336e+06,7.193500e+03,1.685518e+04,0.000000e+00
"II (Incinerator, institutional)",6.777184e+05,4.655000e+02,8.180100e+02,1.736900e+03
K (Kiln),1.014432e+08,2.146068e+05,3.807400e+05,9.174764e+05
Lime Kiln,1.210990e+05,1.250000e+02,2.980000e+02,0.000000e+00
MWC (Municipal waste combustor),9.797240e+07,2.123269e+06,3.329399e+06,1.501774e+08
"NGLH (Heater, natural gas line)",3.276997e+06,1.429072e+03,1.748618e+03,1.597580e+03
O (Oven),2.361732e+06,6.740000e+02,1.526356e+03,0.000000e+00
"OB (Boiler, other)",8.508269e+08,1.041522e+06,2.626362e+06,1.125106e+08
OCS (Other combustion source),4.013702e+09,4.525214e+06,8.457231e+06,1.078680e+08
"OFB (Fluidized bed, other)",1.803513e+06,8.052000e+03,2.350922e+04,1.647603e+06
Other,6.528575e+06,3.091924e+03,3.722033e+03,3.293157e+02
"PCO (Pulverized coal, other)",3.489162e+06,2.386750e+04,4.822713e+04,2.363487e+06
"PCT (Pulverized coal, tangentially-fired)",8.566077e+07,2.513120e+05,4.834213e+05,9.902082e+06
"PCWD (Pulverized coal, wall-fired, dry bottom)",7.501399e+07,1.927062e+05,3.984659e+05,6.901738e+06
"PCWW (Pulverized coal, wall-fired, wet bottom)",4.775418e+06,8.377250e+03,2.042343e+04,0.000000e+00
PD (Product or intermediate product dryer),9.038665e+06,6.543620e+03,9.670452e+03,6.024220e+04
"PFB (Boiler, pressurized fluidized bed)",1.547259e+06,2.054000e+03,4.241136e+03,1.308680e+04
PRH (Process Heater),4.636213e+08,6.462425e+05,1.499978e+06,1.059125e+06
Process Vent,3.455900e+03,1.625000e+00,2.086000e+00,0.000000e+00
Pulp Mill Lime Kiln,5.463573e+07,6.915925e+04,6.133734e+03,0.000000e+00
Q (Other Subpart Q combustion sources not otherwise listed.),8.385853e+05,1.554750e+03,2.653988e+03,1.531000e+02
RCO (Regenerative catalytic oxidizer),1.243148e+05,1.177500e+02,2.240960e+02,0.000000e+00
RICE (Reciprocating internal combustion engine),5.729023e+07,4.357614e+04,7.666434e+04,7.725985e+06
RTO (Regenerative thermal oxidizer),1.788086e+06,1.049750e+03,1.636318e+03,2.517040e+04
S (Stoker Boiler),1.250782e+08,1.446304e+06,4.142982e+06,3.108295e+08
"SCCT (CT (Turbine, simple cycle combustion))",3.266739e+08,1.687315e+05,2.277919e+05,4.517109e+06
Sulfur Recovery Plant,4.264780e+04,2.000000e+01,2.384000e+01,0.000000e+00
"TODF (Thermal oxidizer, direct fired, no heat recovery)",8.749211e+06,1.100925e+04,2.079592e+04,4.149368e+05
Thermal Catalytic Cracking Unit,2.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00
nan,3.853849e+08,3.997109e+05,7.553558e+05,2.112651e+07

In [6]:
unitdata_df['Facility Name'].value_counts()

Facility Name
THE GEORGE WASHINGTON UNIVERSITY                        1146
University of Arizona                                   1125
HILL AIR FORCE BASE: MAIN BASE                          1046
MOTIVA ENTERPRISES LLC                                  1010
Mont Belvieu Complex                                     913
                                                        ...
TARGA ROCKER B COMPRESSOR STATION                          1
Cheyenne Central Processing Facility                       1
Pinnacle Dos Picos Gas Plant                               1
Pinehill Landfill                                          1
1500 South Tibbs LLC d/b/a Aurorium Indianapolis LLC       1
Name: count, Length: 8595, dtype: int64

In [7]:
emissions_by_facility = unitdata_df.groupby('Facility Name')[emissions_cols].sum()
emissions_by_facility

,Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
Facility Name,,,,
1500 South Tibbs LLC d/b/a Aurorium Indianapolis LLC,64740.5,30.50,36.356,0.0
17Z Gas Plant - Chevron USA Inc.,22508.2,10.50,12.516,0.0
23rd and 3rd,821973.3,383.50,461.900,0.0
29-6 #2 Central Delivery Point,75504.1,35.50,44.104,0.0
30-30 Gas Plant,69521.3,32.50,38.740,0.0
...,...,...,...,...
Zion Energy Center,2687912.7,1248.25,1530.826,0.0
Zuni,199692.3,92.50,107.280,0.0
voestalpine Texas,35497.8,16.75,19.966,0.0
voestalpine Texas LLC,134027.9,63.25,75.394,0.0
white oak landfill,9.7,0.00,0.000,5.1

In [8]:
emissions_by_state = unitdata_df.groupby('State')[emissions_cols].sum()
emissions_by_state

,Unit CO2 emissions (non-biogenic),Unit Methane (CH4) emissions,Unit Nitrous Oxide (N2O) emissions,Unit Biogenic CO2 emissions (metric tons)
State,,,,
AK,1.938444e+08,1.426098e+05,2.252397e+05,8.328200e+04
AL,9.327701e+08,2.123092e+06,4.206686e+06,6.049434e+07
AR,4.814009e+08,1.231419e+06,2.259335e+06,2.046698e+07
AZ,6.157479e+08,1.251864e+06,2.156788e+06,3.695697e+06
CA,8.910454e+08,7.356070e+05,1.249236e+06,2.169728e+07
CO,5.147126e+08,6.113235e+05,2.016980e+06,1.292823e+06
CT,1.245735e+08,2.637634e+05,4.087915e+05,1.418688e+07
DC,3.622566e+06,1.967000e+03,2.673358e+03,6.550000e+03
DE,6.723827e+07,5.983488e+04,1.199769e+05,1.760865e+05
FL,1.412109e+09,2.823613e+06,4.844503e+06,1.203646e+08
GA,7.884418e+08,2.005269e+06,3.917837e+06,6.218882e+07
GU,1.565204e+07,1.530425e+04,3.648772e+04,0.000000e+00
HI,9.917494e+07,2.090922e+05,3.991128e+05,8.332462e+06
IA,5.700116e+08,1.072057e+06,2.177824e+06,3.460275e+06
ID,5.043142e+07,8.737425e+04,1.864681e+05,6.075902e+06
IL,1.170242e+09,2.695349e+06,4.800522e+06,3.292447e+06
IN,1.497515e+09,2.846295e+06,5.392282e+06,7.992264e+06
KS,4.090384e+08,5.051326e+05,1.733201e+06,6.457428e+05
KY,9.855216e+08,2.319032e+06,4.839212e+06,7.858924e+06
LA,1.346120e+09,1.662135e+06,3.696586e+06,4.031518e+07
MA,1.557202e+08,4.316410e+05,6.698240e+05,2.273992e+07
MD,2.281540e+08,5.254132e+05,1.054647e+06,1.015450e+07
ME,3.985441e+07,3.053605e+05,6.750089e+05,2.638196e+07
MI,9.080573e+08,1.510914e+06,3.630077e+06,2.658158e+07
MN,4.444075e+08,6.733942e+05,2.204563e+06,2.839982e+07
MO,8.510549e+08,1.381187e+06,4.019498e+06,1.396478e+06
MS,4.231849e+08,6.413194e+05,1.229040e+06,1.668570e+07
MT,2.256805e+08,5.816755e+05,1.057381e+06,2.592186e+06
NC,6.869892e+08,1.670338e+06,3.092367e+06,2.873924e+07
ND,4.644815e+08,1.051239e+06,1.909558e+06,5.072194e+05
NE,3.568942e+08,4.836339e+05,1.567119e+06,1.284984e+06
NH,3.854686e+07,8.482319e+04,1.642465e+05,7.386537e+06
NJ,2.605980e+08,4.124649e+05,6.637932e+05,1.517566e+07
NM,3.548134e+08,7.551415e+05,1.294817e+06,1.880250e+04
NV,2.077045e+08,2.255707e+05,3.568887e+05,3.310229e+05
NY,4.545130e+08,7.292731e+05,1.205900e+06,3.777083e+07
OH,1.315725e+09,2.301296e+06,4.786883e+06,5.056991e+06
OK,6.154815e+08,1.055246e+06,1.846084e+06,7.512809e+06
OR,1.340127e+08,2.443965e+05,4.770760e+05,1.413795e+07
PA,1.351396e+09,2.113400e+06,4.598485e+06,2.878361e+07
PR,1.793439e+08,2.245085e+05,4.452931e+05,7.307900e+04
RI,4.254523e+07,1.997420e+04,2.449411e+04,0.000000e+00
SC,4.226205e+08,1.184733e+06,2.346676e+06,4.373183e+07
SD,6.061397e+07,1.125768e+05,2.007540e+05,1.930491e+06
TN,5.139862e+08,1.056468e+06,2.467203e+06,1.681505e+07
TX,4.159508e+09,5.592616e+06,1.220737e+07,2.428455e+07
UT,4.337836e+08,1.069466e+06,1.876750e+06,4.638081e+05
VA,4.504782e+08,9.858234e+05,1.830914e+06,4.153287e+07
VI,1.511554e+07,1.643550e+04,3.647550e+04,0.000000e+00
VT,1.908921e+06,6.944750e+03,1.078879e+04,8.051934e+05
WA,2.253096e+08,5.722147e+05,1.221251e+06,2.910492e+07
WI,5.891993e+08,5.220614e+05,2.736896e+06,2.545479e+07
WV,8.507615e+08,1.639627e+06,4.093693e+06,5.974000e+02
WY,6.724833e+08,1.570265e+06,2.964996e+06,6.784500e+03

### **fuel data sheet**

In [9]:
fueldata_df = pd.read_excel('/Users/sophiekim/Desktop/msds/ds 5030/project/emissions_by_unit_and_fuel_type_c_d_aa.xlsb', engine='pyxlsb', skiprows=5, sheet_name='FUEL_DATA')

fueldata_df

,Facility Id,FRS Id,Facility Name,City,State,Primary NAICS Code,Reporting Year,Industry Type (subparts),Industry Type (sectors),Unit Name,General Fuel Type,Specific Fuel Type,Other Fuel Name,Blend Fuel Name,Fuel Methane (CH4) emissions (mt CO2e),Fuel Nitrous Oxide (N2O) emissions (mt CO2e)
0,1001155,1.100004e+11,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199.0,2023,C,Chemicals,GP-1,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,30.50,36.356
1,1001155,1.100004e+11,1500 South Tibbs LLC d/b/a Aurorium Indianapol...,Indianapolis,IN,325199.0,2023,C,Chemicals,GP-1,Petroleum Products,Naphtha (<401 deg F),NaN,NaN,0.00,0.000
2,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130.0,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.00,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,1.50,1.788
3,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130.0,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.01,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,0.00,0.000
4,1012147,NaN,17Z Gas Plant - Chevron USA Inc.,McKittrick,CA,211130.0,2018,"C,NN,W","Natural Gas and Natural Gas Liquids Suppliers,...",CP-03.02,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,0.00,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323491,1003318,1.100438e+11,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111.0,2015,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,16.00,19.072
323492,1003318,1.100438e+11,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111.0,2014,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,15.50,18.476
323493,1003318,1.100438e+11,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111.0,2013,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,20.25,24.138
323494,1003318,1.100438e+11,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111.0,2012,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,22.00,26.224
323495,1003318,1.100438e+11,ZYBACH CRYOGENIC PLANT,Briscoe,TX,211111.0,2011,"C,W",Petroleum and Natural Gas Systems,GP-Zybach,Natural Gas,Natural Gas (Weighted U.S. Average),NaN,NaN,25.25,30.098

In [10]:
fueldata_df.columns

Index(['Facility Id', 'FRS Id', 'Facility Name', 'City', 'State',
       'Primary NAICS Code', 'Reporting Year', 'Industry Type (subparts)',
       'Industry Type (sectors)', 'Unit Name', 'General Fuel Type',
       'Specific Fuel Type', 'Other Fuel Name', 'Blend Fuel Name',
       'Fuel Methane (CH4) emissions (mt CO2e)',
       'Fuel Nitrous Oxide (N2O) emissions (mt CO2e)'],
      dtype='object')

In [11]:
fueldata_df['General Fuel Type'].value_counts()

General Fuel Type
Natural Gas           185963
Petroleum Products     84954
Other                  37379
Coal                   15149
Fuel Gas                  17
Natural Gas                2
Biomass                    2
Solid Byproducts           1
Name: count, dtype: int64

In [12]:
fuel_cols = ['Fuel Methane (CH4) emissions (mt CO2e)',
       'Fuel Nitrous Oxide (N2O) emissions (mt CO2e)']

emissions_by_fuel = fueldata_df.groupby('General Fuel Type')[fuel_cols].sum()
emissions_by_fuel

,Fuel Methane (CH4) emissions (mt CO2e),Fuel Nitrous Oxide (N2O) emissions (mt CO2e)
General Fuel Type,,
Biomass,4.000000e+00,4.768000e+00
Coal,3.810367e+07,8.239497e+07
Fuel Gas,2.026750e+03,4.829090e+03
Natural Gas,5.313865e+06,6.338404e+06
Natural Gas,1.032500e+02,1.230740e+02
Other,1.047312e+07,2.369679e+07
Petroleum Products,5.193649e+05,1.200900e+06
Solid Byproducts,0.000000e+00,0.000000e+00

In [13]:
fueldata_df['Facility Name'].value_counts()

Facility Name
THE GEORGE WASHINGTON UNIVERSITY       1232
HILL AIR FORCE BASE: MAIN BASE         1151
University of Arizona                  1125
MOTIVA ENTERPRISES LLC                 1058
Mont Belvieu Complex                    919
                                       ...
North Canton Compressor Station           1
KaMin LLC - Edgar                         1
TARGA ROCKER B COMPRESSOR STATION         1
LIVE OAK LANDFILL & RECYLING CENTER       1
Wellhead Power Gates, LLC                 1
Name: count, Length: 8595, dtype: int64

In [14]:
fuels_by_facility = fueldata_df.groupby('Facility Name')[fuel_cols].sum()
fuels_by_facility

,Fuel Methane (CH4) emissions (mt CO2e),Fuel Nitrous Oxide (N2O) emissions (mt CO2e)
Facility Name,,
1500 South Tibbs LLC d/b/a Aurorium Indianapolis LLC,30.50,36.356
17Z Gas Plant - Chevron USA Inc.,10.50,12.516
23rd and 3rd,383.50,461.900
29-6 #2 Central Delivery Point,35.50,44.104
30-30 Gas Plant,32.50,38.740
...,...,...
Zion Energy Center,1248.25,1530.826
Zuni,92.50,107.280
voestalpine Texas,16.75,19.966
voestalpine Texas LLC,63.25,75.394
white oak landfill,0.00,0.000

---